#-------------- TESTING AREA ----------------#

# require_relative './config/config_helper'
# require_relative './config/start'
# require_relative './config/setup'
# require_relative './config/game'
# require_relative './config/game/game_helper'
# require_relative './config/game/character'
# require_relative './config/game/explore'
# require_relative './config/game/inventory'
# require_relative './config/game/item'
# require_relative './config/game/game_attribute/level_controller'
# require_relative './config/game/game_items/potion'
# require_relative './config/game/game_items/accessory'
# require_relative './config/game/game_items/armor'
# require_relative './config/game/game_items/weapon'
# require_relative './config/game/game_record/load_record'
# require_relative './config/game/game_record/save_record'
# require_relative './config/game/monster/monster'
# require_relative './config/game/monster/monster_fight'
# require_relative './config/game/monster/battle_helper'
# require_relative './config/game/monster/escape_battle'
