##### Used Token in RubyRPG #####

$PROCESS_GAME_TOKEN
$QUIT_GAME_TOKEN
$SELECT_TOKEN
$RANDOM_TOKEN

$RECORD_ID
$RECORD_FILE_NAME
$RECORD_INVENTORY_ITEMS_FILE_NAME
$RECORD_FOLDER_PATH
$RECORD_ITEMS_FOLDER_PATH
$RECORD_FILES

$CHARACTER
$CHARACTER_NAME
$CHARACTER_LEVEL
$CHARACTER_MAX_HP
$CHARACTER_MAX_MP
$CHARACTER_MAX_EXP
$CHARACTER_ATTACK
$CHARACTER_DEFENSE
$CHARACTER_AGILITY
$CHARACTER_CRITICAL_ATTACK_RATE
$CHARACTER_LUCK
$CHARACTER_MONEY
$CHARACTER_INVENTORY

$BATTLE_START_TOKEN

$CURRENT_MONSTER

$MONSTER_DATABASE
$POTION_DATABASE
$ACCESSORY_DATABASE

